#try serve pra tentar realizar oq to pedindo
#except serve para tratar o erro
#previne falhas
#melhor experiencia
#manutenção
#exemplo
num1=input('digite o primeiro numero:')
num2=input('digite o segundo numero:')
try:
     num1=int(num1) 
     num1=int(num1) 
     print(f'a soma dos numeros é:{num1+num2}')
except:

     print('digite um numero correto!')
